name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: lukebrowne/the-times-pdf/the-times-pdf
          tags: latest
          tag_with_sha: true
