name: Deliver
on:
  workflow_dispatch:
  schedule:
    - cron: "12 06 * * *"
jobs:
  deliver:
    name: Deliver newspaper
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Authenticate with GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: docker pull docker.pkg.github.com/lukebrowne/the-times-pdf/the-times-pdf:latest
      - name: Run delivery
        run: |
          docker run -i --rm --privileged \
            -e TIMES_EMAIL=$TIMES_EMAIL -e TIMES_PASSWORD=$TIMES_PASSWORD \
            -e SLACK_CHANNEL=$SLACK_CHANNEL -e SLACK_TOKEN=$SLACK_TOKEN \
            docker.pkg.github.com/lukebrowne/the-times-pdf/the-times-pdf:latest
        env:
          TIMES_EMAIL: ${{ secrets.TIMES_EMAIL }}
          TIMES_PASSWORD: ${{ secrets.TIMES_PASSWORD }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
